### ISSUE TITLE
关于保持图片清晰度

### ISSUE THREAD

**Issue by Vespa314** [sylnsfar/qrcode#11]
我看代码中对传入的图片是做了resize压缩处理，如果传入的图片长宽像素值比较大（但是相等），可否在不压缩的情况下生成高清的背景？

这也牵扯出另一个问题，二维码中的黑白点可否支持设置点的大小，而不是固定一个像素。

本来想自己修改修改的，但是发现代码中hardcode太多了。。

**Comment by sylnsfar** [comment]
高清背景是可以的，但那是另一种风格了
