### ISSUE TITLE
加一种二维码格式，就是中间嵌入清晰方格logo的二维码

### ISSUE THREAD

**Issue by leo-yi** [sylnsfar/qrcode#25]
如题，希望作者有空能实现，谢谢～

**Comment by hick** [comment]
哈哈哈   我也比较各种花色蛮多, 这种没有实现是啥情况?

**Comment by QuietWind** [comment]
> 可以通过pillow自行在中间添加
> 
> ```python
> import os
> from PIL import Image
> 
> 
> if __name__ == '__main__':
>     big_image = Image.open('./qr_code_logo/1.png')
>     small_image = Image.open('logo.png')
>     # small_image.show()
>     small_image.thumbnail((100, 100))  # 可以实现压缩
>     big_image.paste(small_image, (170, 170))
>     # big_image.show()
> ```

你实现的，有效果图？

**Comment by CZacker** [comment]
图一是二维码的结构原理，图二是具体效果图
![图1](http://image109.360doc.com/DownloadImg/2018/02/2210/125228431_4_20180222102308895.png)
![图2](https://user-images.githubusercontent.com/25023285/64942726-6dca8f00-d89c-11e9-9c00-d9aaa490f19f.png)

**Comment by CZacker** [comment]
> > 可以通过pillow自行在中间添加
> > ```python
> > import os
> > from PIL import Image
> > 
> > 
> > if __name__ == '__main__':
> >     big_image = Image.open('./qr_code_logo/1.png')
> >     small_image = Image.open('logo.png')
> >     # small_image.show()
> >     small_image.thumbnail((100, 100))  # 可以实现压缩
> >     big_image.paste(small_image, (170, 170))
> >     # big_image.show()
> > ```
> 
> 你实现的，有效果图？

在上述评论
