### ISSUE TITLE
可以厚脸皮的要下你例子中的熊本熊和龙猫的图片吗。。。

### ISSUE THREAD

**Issue by MinionsDave** [sylnsfar/qrcode#31]
可以厚脸皮的要你例子中的熊本熊和龙猫的图片吗。。。我发现我网络上找的图片，都达不到你的萌萌哒的效果😊

**Comment by sylnsfar** [comment]
尽量找了下（如果你还需要的话。。。
https://shurufacdn.baidu.com/shurufa/201608162301080625.gif
https://www.pinterest.com/pin/827958712737461312/
