### ISSUE TITLE
A dependency-free executable 

### ISSUE THREAD

**Issue by mohsen1** [sylnsfar/qrcode#4]
Can you package this program into a self-contained program (maybe via [PyInstaller](http://www.pyinstaller.org/)) so user don't have to install dependencies. I was blocked on decencies installation when I wanted to try it.

**Comment by sylnsfar** [comment]
Thank you for advice, but actually I have packaged it already and added the update into [qrcode-README](https://github.com/sylnsfar/qrcode#qr-code).
See the package at this [qrcode_win repo](https://github.com/sylnsfar/qrcode_win).

**Comment by mohsen1** [comment]
I don't have a Windows machine. I should've clarified that I'm on Mac.

**Comment by Maras0830** [comment]
@mohsen1 see [www.amazing-qrcode.com](www.amazing-qrcode.com)

**Comment by sylnsfar** [comment]
@mohsen1 Now you maybe don't need a package while having the web version. (actually I still have tried to package this on Windows, but it seemed to be futile without a Mac)

**Comment by mohsen1** [comment]
The web version works great! Thanks!
