### ISSUE TITLE
用提示文档的方式形成的彩色二维码很模糊（无彩色且看不清艺术

### ISSUE THREAD

**Issue by JerryNile** [sylnsfar/qrcode#60]
![github_qrcode](https://user-images.githubusercontent.com/39849691/78802689-b1c7e180-79f0-11ea-8035-0300da5a0b72.png)

**Comment by JerryNile** [comment]
Had sovled

**Comment by shijianzugouniai** [comment]
您知道怎么生成动态二维码吗？就是与自己下载的一个GIF结合，与网页链接结合生成动态二维码，这一项好像一直不行，试了很多次了
