### ISSUE TITLE
楼主，可否告诉下你的那张狐狸与兔子的命令行参数啊求科普

### ISSUE THREAD

**Issue by jinjingcai2014** [sylnsfar/qrcode#7]
我在网上下载了一张相片，始终达不到楼主兔子与狐狸那张相片那么好看，求科普

**Comment by sylnsfar** [comment]
你指的是动态的还是静态的？动态图大概是 `-con 1.5 -bri 1.9` 。静态的因为原图已经删了，我也不清楚，不过也应该是在1.0和2.0之间。
